export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";


export const USER_GET_REQUEST = "USER_GET_REQUEST";
export const USER_GET_ERROR = "USER_GET_ERROR";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";

export const USER_ADD_REQUEST = "USER_ADD_REQUEST";
export const USER_ADD_ERROR = "USER_ADD_ERROR";
export const USER_ADD_SUCCESS = "USER_ADD_SUCCESS";

export const AUCTION_ADD_REQUEST = "AUCTION_ADD_REQUEST";
export const AUCTION_ADD_ERROR = "AUCTION_ADD_ERROR";
export const AUCTION_ADD_SUCCESS = "AUCTION_ADD_SUCCESS";

export const AUCTION_GET_REQUEST = "AUCTION_GET_REQUEST";
export const AUCTION_GET_ERROR = "AUCTION_GET_ERROR";
export const AUCTION_GET_SUCCESS = "AUCTION_GET_SUCCESS";

export const AUCTION_EDIT_REQUEST = "AUCTION_EDIT_REQUEST";
export const AUCTION_EDIT_ERROR = "AUCTION_EDIT_ERROR";
export const AUCTION_EDIT_SUCCESS = "AUCTION_EDIT_SUCCESS";