export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";


export const USER_GET_REQUEST = "USER_GET_REQUEST";
export const USER_GET_ERROR = "USER_GET_ERROR";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";

export const USER_ADD_REQUEST = "USER_ADD_REQUEST";
export const USER_ADD_ERROR = "USER_ADD_ERROR";
export const USER_ADD_SUCCESS = "USER_ADD_SUCCESS";