export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";


export const USER_GET_REQUEST = "USER_GET_REQUEST";
export const USER_GET_ERROR = "USER_GET_ERROR";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";

export const USER_ADD_REQUEST = "USER_ADD_REQUEST";
export const USER_ADD_ERROR = "USER_ADD_ERROR";
export const USER_ADD_SUCCESS = "USER_ADD_SUCCESS";

export const AUCTION_ADD_REQUEST = "AUCTION_ADD_REQUEST";
export const AUCTION_ADD_ERROR = "AUCTION_ADD_ERROR";
export const AUCTION_ADD_SUCCESS = "AUCTION_ADD_SUCCESS";

export const AUCTION_GET_REQUEST = "AUCTION_GET_REQUEST";
export const AUCTION_GET_ERROR = "AUCTION_GET_ERROR";
export const AUCTION_GET_SUCCESS = "AUCTION_GET_SUCCESS";

export const AUCTION_EDIT_REQUEST = "AUCTION_EDIT_REQUEST";
export const AUCTION_EDIT_ERROR = "AUCTION_EDIT_ERROR";
export const AUCTION_EDIT_SUCCESS = "AUCTION_EDIT_SUCCESS";


export const AUCTION_GET_ID_REQUEST = "AUCTION_GET_ID_REQUEST";
export const AUCTION_GET_ID_ERROR = "AUCTION_GET_ID_ERROR";
export const AUCTION_GET_ID_SUCCESS = "AUCTION_GET_ID_SUCCESS";

export const JEWELERY_GET_REQUEST = "JEWELERY_GET_REQUEST";
export const JEWELERY_GET_ERROR = "JEWELERY_GET_ERROR";
export const JEWELERY_GET_SUCCESS = "JEWELERY_GET_SUCCESS";

export const JEWELERY_ATTRIBUTE_GET_REQUEST = "JEWELERY_ATTRIBUTE_GET_REQUEST";
export const JEWELERY_ATTRIBUTE_GET_ERROR = "JEWELERY_ATTRIBUTE_GET_ERROR";
export const JEWELERY_ATTRIBUTE_GET_SUCCESS = "JEWELERY_ATTRIBUTE_GET_SUCCESS";

export const PICKLIST_GET_REQUEST = "PICKLIST_GET_REQUEST";
export const PICKLIST_GET_ERROR = "PICKLIST_GET_ERROR";
export const PICKLIST_GET_SUCCESS = "PICKLIST_GET_SUCCESS";


export const COLLECTION_GET_REQUEST = "COLLECTION_GET_REQUEST";
export const COLLECTION_GET_ERROR = "COLLECTION_GET_ERROR";
export const COLLECTION_GET_SUCCESS = "COLLECTION_GET_SUCCESS";

export const COLLECTION_ADD_REQUEST = "COLLECTION_ADD_REQUEST";
export const COLLECTION_ADD_ERROR = "COLLECTION_ADD_ERROR";
export const COLLECTION_ADD_SUCCESS = "COLLECTION_ADD_SUCCESS";


export const COLLECTION_EDIT_REQUEST = "COLLECTION_EDIT_REQUEST";
export const COLLECTION_EDIT_ERROR = "COLLECTION_EDIT_ERROR";
export const COLLECTION_EDIT_SUCCESS = "COLLECTION_EDIT_SUCCESS";

export const AUCTION_ITEM_GET_REQUEST = "AUCTION_ITEM_GET_REQUEST";
export const AUCTION_ITEM_GET_ERROR = "AUCTION_ITEM_GET_ERROR";
export const AUCTION_ITEM_GET_SUCCESS = "AUCTION_ITEM_GET_SUCCESS";

export const AUCTION_ITEM_ADD_REQUEST = "AUCTION_ITEM_ADD_REQUEST";
export const AUCTION_ITEM_ADD_ERROR = "AUCTION_ITEM_ADD_ERROR";
export const AUCTION_ITEM_ADD_SUCCESS = "AUCTION_ITEM_ADD_SUCCESS";

export const JEWELERY_DDL_ADD_REQUEST = "JEWELERY_DDL_ADD_REQUEST";
export const JEWELERY_DDL_ADD_ERROR = "JEWELERY_DDL_ADD_ERROR";
export const JEWELERY_DDL_ADD_SUCCESS = "JEWELERY_DDL_ADD_SUCCESS";

export const AUCTION_ITEM_DETAILS_GET_REQUEST = "AUCTION_ITEM_DETAILS_GET_REQUEST";
export const AUCTION_ITEM_DETAILS_GET_ERROR = "AUCTION_ITEM_DETAILS_GET_ERROR";
export const AUCTION_ITEM_DETAILS_GET_SUCCESS = "AUCTION_ITEM_DETAILS_GET_SUCCESS";

export const AUCTION_ITEM_EDIT_REQUEST = "AUCTION_ITEM_EDIT_REQUEST";
export const AUCTION_ITEM_EDIT_ERROR = "AUCTION_ITEM_EDIT_ERROR";
export const AUCTION_ITEM_EDIT_SUCCESS = "AUCTION_ITEM_EDIT_SUCCESS";


export const JEWELERY_ADD_REQUEST = "JEWELERY_ADD_REQUEST";
export const JEWELERY_ADD_ERROR = "JEWELERY_ADD_ERROR";
export const JEWELERY_ADD_SUCCESS = "JEWELERY_ADD_SUCCESS";


export const JEWELERY_EDIT_REQUEST = "JEWELERY_EDIT_REQUEST";
export const JEWELERY_EDIT_ERROR = "JEWELERY_EDIT_ERROR";
export const JEWELERY_EDIT_SUCCESS = "JEWELERY_EDIT_SUCCESS";

export const JEWELERY_ATTRIBUTE_ADD_REQUEST = "JEWELERY_ATTRIBUTE_ADD_REQUEST";
export const JEWELERY_ATTRIBUTE_ADD_ERROR = "JEWELERY_ATTRIBUTE_ADD_ERROR";
export const JEWELERY_ATTRIBUTE_ADD_SUCCESS = "JEWELERY_ATTRIBUTE_ADD_SUCCESS";

export const JEWELERY_ATTRIBUTE_EDIT_REQUEST = "JEWELERY_ATTRIBUTE_EDIT_REQUEST";
export const JEWELERY_ATTRIBUTE_EDIT_ERROR = "JEWELERY_ATTRIBUTE_EDIT_ERROR";
export const JEWELERY_ATTRIBUTE_EDIT_SUCCESS = "JEWELERY_ATTRIBUTE_EDIT_SUCCESS";

export const ATTRIBUTE_PICKLIST_GET_REQUEST = "ATTRIBUTE_PICKLIST_GET_REQUEST";
export const ATTRIBUTE_PICKLIST_GET_ERROR = "ATTRIBUTE_PICKLIST_GET_ERROR";
export const ATTRIBUTE_PICKLIST_GET_SUCCESS = "ATTRIBUTE_PICKLIST_GET_SUCCESS";